### ISSUE TITLE
Special tests for Onedrive on win 8.1

### ISSUE THREAD

**Issue by KaiSta** [KaiSta/tempest#11]
Onedrive uses "filestubs" in win8.1 and downloads the file on demand. Needs to be tested if this works with the backend.

**Comment by KaiSta** [comment]
Smartfiles won't work without enabling an extra option in the program properties, which must be done by the scrates user. ("Compatibility -> "Enable this program to work with OneDrive files"). Still no other fix.

**Comment by jochenklein** [comment]
And what if this option is always enabled for Windows users only? So they don't have to take care about it.

**Comment by KaiSta** [comment]
compatibility settings must be set by the user. The GUI could notify him if the registry key under HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers for Scrates doesn't contain ~PLACEHOLDERFILES.
